// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQeArq9WjkrnBcl5wrRArYZGIlEM_ksD0',
    appId: '1:147633863958:web:a6806e87eb96ce2d126437',
    messagingSenderId: '147633863958',
    projectId: 'chatapp-ecbff',
    authDomain: 'chatapp-ecbff.firebaseapp.com',
    storageBucket: 'chatapp-ecbff.appspot.com',
    measurementId: 'G-H9FWVYFL7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFsRAZANFiNvMPi2F7Sk9xjC93RPlpNdg',
    appId: '1:147633863958:android:69b8026f78b37538126437',
    messagingSenderId: '147633863958',
    projectId: 'chatapp-ecbff',
    storageBucket: 'chatapp-ecbff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD33Pl5LzmqSeL3WnJeTmJIK5NQyoHh0IA',
    appId: '1:147633863958:ios:e2b224a8b88b5799126437',
    messagingSenderId: '147633863958',
    projectId: 'chatapp-ecbff',
    storageBucket: 'chatapp-ecbff.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD33Pl5LzmqSeL3WnJeTmJIK5NQyoHh0IA',
    appId: '1:147633863958:ios:e2b224a8b88b5799126437',
    messagingSenderId: '147633863958',
    projectId: 'chatapp-ecbff',
    storageBucket: 'chatapp-ecbff.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQeArq9WjkrnBcl5wrRArYZGIlEM_ksD0',
    appId: '1:147633863958:web:88719e43aff1cfc6126437',
    messagingSenderId: '147633863958',
    projectId: 'chatapp-ecbff',
    authDomain: 'chatapp-ecbff.firebaseapp.com',
    storageBucket: 'chatapp-ecbff.appspot.com',
    measurementId: 'G-MKKQJ0WRCJ',
  );
}
